# -*- coding: utf-8 -*-
"""Filtrado y preprocesamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vWGVi9YN1YP8FQkq4Dy8VlvQA_8sKQFm
"""

import serial
import time
import numpy as np

#Parámetros del Sistema
SERIAL_PORT = 'COM3'
BAUD_RATE = 115200
ADC_RESOLUTION_BITS = 10
ADC_MAX_VALUE = 2**ADC_RESOLUTION_BITS - 1
REFERENCE_VOLTAGE = 5.0
SAMPLE_RATE_HZ = 50

#Parámetros de Procesamiento
BUFFER_SIZE = 100
sample_buffer = []

#Simulación de Filtro (Promedio Móvil)
FILTER_WINDOW = 5

def apply_moving_average_filter(data_array, window):
    weights = np.ones(window) / window
    return np.convolve(data_array, weights, mode='valid')

#Conexión Serial y Muestreo
try:
    ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=1)
    print(f"Conexión establecida con Arduino en {SERIAL_PORT} a {BAUD_RATE} baudios.")
    time.sleep(2)

    print("\nIniciando lectura de muestras. Presiona Ctrl+C para detener.\n")

    while True:
        if ser.in_waiting > 0:
            line = ser.readline().decode('utf-8').strip()

            try:
                raw_sample = int(line)

                sample_buffer.append(raw_sample)

                if len(sample_buffer) >= BUFFER_SIZE:

                    print("-" * 40)
                    print(f"Bloque de {BUFFER_SIZE} muestras listo para procesamiento.")

                    raw_data_block = np.array(sample_buffer)

                    # 1. Normalización y Mapeo a Voltaje
                    voltage_block = (raw_data_block / ADC_MAX_VALUE) * REFERENCE_VOLTAGE
                    print(f"Voltaje promedio del bloque: {np.mean(voltage_block):.3f} V")

                    # 2. Aplicación de Teorema de Nyquist/Filtro (Simulado)
                    filtered_block = apply_moving_average_filter(voltage_block, FILTER_WINDOW)
                    print(f"Número de muestras después del filtrado: {len(filtered_block)}")

                    # 3. Conversión a Muestras Normalizadas (Para Codificación de Fuente)
                    data_for_source_coding = (filtered_block / REFERENCE_VOLTAGE) * ADC_MAX_VALUE
                    data_for_source_coding = np.round(data_for_source_coding).astype(int)

                    print(f"Primeros 5 datos para la Codificación de Fuente: {data_for_source_coding[:5]}")
                    print("-" * 40)

                    sample_buffer = []

            except ValueError:
                pass

except serial.SerialException as e:
    print(f"ERROR: No se pudo conectar al puerto {SERIAL_PORT}. Verifica el puerto y que Arduino no esté en uso. Detalles: {e}")
except KeyboardInterrupt:
    print("\nDeteniendo la lectura de datos por el usuario.")
finally:
    if 'ser' in locals() and ser.is_open:
        ser.close()
        print("Conexión serial cerrada.")